sudo: required
services:
  - docker

before_install: 
  - docker build -t kashnaladak/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true kashnaladak/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-676206909831"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
